service: aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource: "*"
  environment:
    NODE_ENV: production

plugins:
 - serverless-apigw-binary
custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  hello:
    handler: bin/handler.app
    events:
      - http: ANY {proxy+}
