service: aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  stage: dev
  region: ap-northeast-2
  environment:
    NODE_ENV: production

plugins:
 - serverless-apigw-binary
custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  hello:
    handler: handler.app
    events:
      - http: ANY {proxy+}
