version: 2
jobs:
  build:
    docker:
      - image: docker:stable
      - image: novemberde/node-awscli
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      # Build
      - run: npx tsc
      - run: exit 1
  test:
    docker:
      - image: novemberde/node-awscli
    working_directory: ~/repo
    steps:
      - checkout
      # - run: ls -al
      - run: npm install
      # Build
      - run: npx tsc
      # Test
      - run: npm test
  deployDev:
    docker:
      - image: novemberde/node-awscli
    working_directory: ~/repo
    steps:
      - checkout
      # - run: ls -al
      - run: npm install
      # Build
      - run: npx tsc
      - run: npx serverless deploy --stage dev
  deployProd:
    docker:
      - image: novemberde/node-awscli
    working_directory: ~/repo
    steps:
      - checkout
      # - run: ls -al
      - run: npm install
      # Build
      - run: npx tsc
      - run: npx serverless deploy --stage prod
      
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployDev:
          requires:
            - test
      - hold:
          type: approval
          requires:
           - deployDev
      - deployProd:
          requires:
            - hold
      # - deploy:
      #     requires:
      #       - test2