version: 2
jobs:
  build:
    docker:
      - image: novemberde/node-awscli
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Build
      - run: npx tsc
  test:
    docker:
      - image: novemberde/node-awscli
    working_directory: ~/repo
    steps:
      - checkout
      - run: ls -al
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      # - run: npm install
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      # # Build
      # - run: npx tsc

      # # Test
      # - run: npm test
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - test2